### ISSUE TITLE
StatusCode.UNAVAILABLE

### ISSUE THREAD

**Issue by gwajnberg** [dgraph-io/pydgraph#176] opened 2022-01-31 22:08 UTC
Hello,
I am using dgraph version 21.12, pydgraph version 21.3.2
I am trying the following code:

```python
import pydgraph

client_stub = pydgraph.DgraphClientStub('localhost:8080')
client = pydgraph.DgraphClient(client_stub)



schema = """
    name: string @index(exact) .
    friend: [uid] @reverse .
    age: int .
    married: bool .
    loc: geo .
    dob: datetime .

    type Person {
        name
        friend
        age
        married
        loc
        dob
    }
    """
client.alter(pydgraph.Operation(schema=schema))
```

and here is the error:
```
Traceback (most recent call last):

  File "C:\Users\gabri\project_cfia\excelparsing-main\untitled0.py", line 25, in <module>
    client.alter(pydgraph.Operation(schema=schema))

  File "C:\Users\gabri\miniconda3\lib\site-packages\pydgraph\client.py", line 127, in alter
    self._common_except_alter(error)

  File "C:\Users\gabri\miniconda3\lib\site-packages\pydgraph\client.py", line 137, in _common_except_alter
    raise error

  File "C:\Users\gabri\miniconda3\lib\site-packages\pydgraph\client.py", line 113, in alter
    return self.any_client().alter(operation, timeout=timeout,

  File "C:\Users\gabri\miniconda3\lib\site-packages\pydgraph\client_stub.py", line 50, in alter
    return self.stub.Alter(operation, timeout=timeout, metadata=metadata,

  File "C:\Users\gabri\miniconda3\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)

  File "C:\Users\gabri\miniconda3\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1643666390.436000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3135,"referenced_errors":[{"created":"@1643666390.436000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

Any help ???

**Comment by MaxxReis** [comment] 2022-10-31 15:21
Hi @gwajnberg I couldn't reproduce the same error, i'm using dgraph v22.0.0 and pydgraph v21.3.1.
Could you share the yaml? 

In this thread there is a resolution for the same error with changing the port: 

https://discuss.dgraph.io/t/status-statuscode-unavailable-details-failed-to-connect-to-all-addresses/11415/5 

I hope it helps!

**Comment by mangalaman93** [comment] 2023-03-22 11:50
closing the issue, changing the port to 9080 should help here. Please feel free to reopen the issue if needed.

**Closed by mangalaman93** 2023-03-22 11:50 UTC
